"""
Version information for MergerMeter application.
This file is AUTO-GENERATED by update_version.py from CHANGELOG.json.
Do not manually edit this file - update CHANGELOG.json instead and run update_version.py.

To update the version:
1. Edit CHANGELOG.json and add a new version entry at the top
2. Run: python apps/mergermeter/update_version.py
"""

__version__ = "1.0.0"

# Note: Version history is maintained in CHANGELOG.json
# This file is automatically updated by update_version.py

